# Generated by Django 5.2.8 on 2026-06-30 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=24)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField()),
                ('instructions', models.TextField(blank=True)),
                ('delivery_slot', models.CharField(max_length=80)),
                ('payment_method', models.CharField(choices=[('tmoney', 'T-Money'), ('flooz', 'Flooz'), ('virement', 'Virement'), ('cash', 'Espèces')], max_length=20)),
                ('products', models.JSONField(default=list)),
                ('total_amount', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
