# Generated by Django 6.0.6 on 2026-09-07 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_order_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=24, verbose_name='Téléphone')),
                ('subject', models.CharField(blank=True, max_length=150, verbose_name='Sujet')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages de contact',
                'ordering': ['-created_at'],
            },
        ),
    ]
