# Generated by Django 6.0.6 on 2026-09-07 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Intitulé du poste')),
                ('department', models.CharField(blank=True, max_length=120, verbose_name='Département')),
                ('location', models.CharField(default='Lomé, Togo', max_length=120, verbose_name='Lieu')),
                ('contract_type', models.CharField(choices=[('cdi', 'CDI'), ('cdd', 'CDD'), ('stage', 'Stage'), ('interim', 'Intérim'), ('freelance', 'Freelance')], default='cdi', max_length=20, verbose_name='Type de contrat')),
                ('description', models.TextField(verbose_name='Description du poste')),
                ('profile', models.TextField(blank=True, verbose_name='Profil recherché')),
                ('is_active', models.BooleanField(default=True, verbose_name='Publiée')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Offre d'emploi",
                'verbose_name_plural': "Offres d'emploi",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_spontaneous', models.BooleanField(default=False, verbose_name='Candidature spontanée')),
                ('first_name', models.CharField(max_length=60, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=60, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=24, verbose_name='Téléphone')),
                ('position', models.CharField(blank=True, max_length=150, verbose_name='Poste visé')),
                ('cv_link', models.URLField(blank=True, verbose_name='Lien vers le CV')),
                ('message', models.TextField(blank=True, verbose_name='Message / lettre de motivation')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Traitée')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='client.joboffer', verbose_name='Offre visée')),
            ],
            options={
                'verbose_name': 'Candidature',
                'verbose_name_plural': 'Candidatures',
                'ordering': ['-created_at'],
            },
        ),
    ]
